package c.tgm.booksapplication.models.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import c.tgm.booksapplication.models.data.Genre;

import c.tgm.booksapplication.models.data.GenreDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig genreDaoConfig;

    private final GenreDao genreDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        genreDaoConfig = daoConfigMap.get(GenreDao.class).clone();
        genreDaoConfig.initIdentityScope(type);

        genreDao = new GenreDao(genreDaoConfig, this);

        registerDao(Genre.class, genreDao);
    }
    
    public void clear() {
        genreDaoConfig.clearIdentityScope();
    }

    public GenreDao getGenreDao() {
        return genreDao;
    }

}
